# This is a basic workflow to help you get started with Actions

name: Gith Mirror
on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: SachinPereira/CloneIssue@f14884be05e39a9bb45e47d094dd8639e18d6149
        with:
          source-repo: 'https://github.com/open-source-parsers/jsoncpp.git'
          destination-repo: 'https://github.com/SachinPereira/jsoncpp.git'
          destination-github-token: ${{ secrets.TEST_TOKEN }}
          dry-run: 'false'
          follow-tags: 'true'

