# This is a basic workflow to help you get started with Actions

name: Gith Mirror
on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: SachinPereira/CloneIssue@ba1f9877056a1e0095def7fef3b33b82ebf2bbc8
        with:
          source-repo: 'https://github.com/open-source-parsers/jsoncpp.git'
          destination-repo: 'https://github.com/SachinPereira/jsoncpp.git'
          destination-github-token: ${{ secrets.TEST_TOKEN }}
          dry-run: 'false'
          follow-tags: 'true'

