# This is a basic workflow to help you get started with Actions

name: Gith Mirror
on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: SachinPereira/CloneIssue@94cc89ebefbc5b3dcac6abe7e83597854c7efc7a
        with:
          source-repo: 'https://github.com/open-source-parsers/jsoncpp.git'
          destination-repo: 'https://github.com/SachinPereira/jsoncpp.git'
          destination-github-token: ${{ secrets.TEST_TOKEN }}
          dry-run: 'false'
          follow-tags: 'true'

