# This is a basic workflow to help you get started with Actions

name: Gith Mirror
on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: SachinPereira/CloneIssue@e34e94c29208710139e5a8a71e7c639c9ddd2121
        with:
          source-repo: 'https://github.com/open-source-parsers/jsoncpp.git'
          destination-repo: 'https://github.com/SachinPereira/jsoncpp.git'
          destination-github-token: ${{ secrets.TEST_TOKEN }}
          dry-run: 'false'
          follow-tags: 'true'

