# This is a basic workflow to help you get started with Actions

name: Gith Mirror
on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: SachinPereira/CloneIssue@e3415205e37f4477cae0353c8ee0fc0ed2e7110f
        with:
          source-repo: 'https://github.com/open-source-parsers/jsoncpp.git'
          destination-repo: 'https://github.com/sachin/jsoncpp.git'
          destination-github-token: ${{ secrets.TEST_TOKEN }}
          dry-run: 'false'
          follow-tags: 'true'

